version: 2.0

jobs:
  build:
    docker:
      - image: cimg/node:17.4.0
    working_directory: ~/project
    steps:
      - checkout
       build2:
    docker:
      - image: cimg/node:17.4.0
    working_directory: ~/project
    steps:
      - checkout
 
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - build2:
          requires:
            - build
         
